article/urls.py
from django.urls import path

from .views import ArticleListView, ArticleCreateView, ArticleDetailView,CommentUpdateView, ArticleUpdateView, ArticleDeleteView

app_name = "article"
urlpatterns = [
    path('', ArticleListView.as_view(), name="article_list"),
    path('article/<int:pk>/detail/', ArticleDetailView.as_view(), name="detail"),
    path('article/<int:pk>/update/', ArticleUpdateView.as_view(), name="update"),
    path('article/<int:pk>/delete/', ArticleDeleteView.as_view(), name="delete"),
    path('article/<int:pk>/comment', CommentUpdateView.as_view(), name="edit_comment"),
    path('create_article/', ArticleCreateView.as_view(), name="create_article"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("signup.urls")),
    path('', include("article.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    bio = models.TextField(null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Article(models.Model):
    title = models.CharField(max_length=200)
    summary = models.TextField()
    content = models.TextField()
    published_date = models.DateTimeField(default=datetime.datetime.today)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='articles/images/', blank=True, null=True)

    def __str__(self):
        return self.title
    
class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.user} on {self.article}'

article/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'summary','published_date', 'author', 'content',  'image']
        widgets = {
            'published_date': forms.DateInput(attrs={'type': 'date'}),
            'summary': forms.Textarea(attrs={'rows': 3}),
            'content': forms.Textarea(attrs={'rows': 7})
        }

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'rows': 4}),
        }

article/views.py
from django.http import  JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic.edit import UpdateView, DeleteView, CreateView, FormMixin
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin


from .models import Article, Comment

from .forms import ArticleForm, CommentForm


class ArticleListView(ListView):
    model = Article
    template_name = "article/article_list.html"
    context_object_name = "articles"
    ordering = ['-published_date']  # Order articles by published date in descending order


class ArticleDetailView(FormMixin, DetailView):
    model = Article
    template_name = "article/detail.html"
    context_object_name = "article"
    form_class = CommentForm


    def get_success_url(self):
        return reverse('article:detail', kwargs={'pk': self.object.pk})
    
    def get_context_data(self, **kwargs):

        # Add additional context (latest articles) and comments to the template
        context = super().get_context_data(**kwargs)
        context['article_list'] = Article.objects.order_by("-published_date")[:10]
        context['comments'] = self.object.comments.all()

        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()

        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = self.object
            comment.user = request.user
            comment.save()
            return redirect(self.get_success_url())
        else:
            return self.form_invalid(form)

class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = "article/comment_update.html"

    def get_success_url(self):
        return reverse('article:detail', kwargs={'pk': self.object.article.pk})

    def get_context_data(self, **kwargs):

        # Add additional context (latest articles) and comments to the template
        context = super().get_context_data(**kwargs)
        context['article_list'] = Article.objects.order_by("-published_date")[:10]
        context['article'] = self.object.article
        context['comments'] = self.object.article.comments.all()
        # print(context['article'].values)
        return context

    def test_func(self):
        comment = self.get_object()
        return comment.user == self.request.user  # Check if the current user is the comment owner
    

class ArticleCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Article
    form_class = ArticleForm
    template_name = 'article/create_article.html'
    context_object_name = 'article'
    permission_required = 'article.add_article'

    def form_valid(self, form):
        # Handle valid form submission and save the form
        form.save()
        return JsonResponse({'success': True})

    def form_invalid(self, form):
        # Handle invalid form submission and return errors as JSON
        errors = {field: error.get_json_data(escape_html=True) for field, error in form.errors.items()}
        return JsonResponse({'success': False, 'errors': errors})



class ArticleDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Article
    context_object_name = 'article'
    permission_required = 'article.delete_article'


    def delete(self, request, *args, **kwargs):
        # Override delete to return a JSON response
        self.object = self.get_object()
        self.object.delete()
        return JsonResponse({'success': True})

    def post(self, request, *args, **kwargs):
        # Delegate POST requests to the delete method
        return self.delete(request, *args, **kwargs)


class ArticleUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Article
    form_class = ArticleForm
    template_name = 'article/update_article.html'
    context_object_name = 'article'
    permission_required = 'article.change_article'


    def form_valid(self, form):
        # If the form is valid, save it and return a success response
        form.save()
        return JsonResponse({'success': True})

    def form_invalid(self, form):
        # If the form is invalid, return errors as JSON
        errors = {field: error.get_json_data(escape_html=True) for field, error in form.errors.items()}
        return JsonResponse({'success': False, 'errors': errors})






#Article list
# def index(request):
#     article = Article.objects.order_by('-published_date')
#     return render(request , "article/article_list.html", {"article": article})


# Update article
# Update views
# def update(request, id):
#     article = get_object_or_404(Article, pk=id)
#     if request.method == 'POST':
#         form = ArticleForm(request.POST, instance=article)
#         if form.is_valid():
#             form.save()
#             return JsonResponse({'success': True})
#         else:
#             errors = {field: error.get_json_data(escape_html=True) for field, error in form.errors.items()}
#             return JsonResponse({'success': False, 'errors': errors})  
#     else:
#         form = ArticleForm(instance=article)
#     return render(request, 'article/update_article.html', {'form': form})


# Delete view
# def delete(request, id):

#     article = get_object_or_404(Article, pk=id)

#     if request.method == 'POST':

#         article.delete()

#         return JsonResponse({'success': True})
    
#     return JsonResponse({'success': False, 'errors': 'Invalid request method'})  

# Create article
# def detail(request, id):
#     article_list = Article.objects.order_by("-published_date")[:15]
#     article = get_object_or_404(Article, pk=id)
#     return render(request, "article/detail.html", {"article": article, "article_list": article_list})

# # def create_article(request):
#     if request.method == 'POST':
#         form = ArticleForm(request.POST, request.FILES)
#         if form.is_valid():
#             print(request.FILES)
#             form.save()
#             return JsonResponse({'success': True})
#         else:
#             errors = {field: error.get_json_data(escape_html=True) for field, error in form.errors.items()}
#             return JsonResponse({'success': False, 'errors': errors})  
#     else:
#         form = ArticleForm()
#     return render(request, 'article/create_article.html', {'form': form})

article/templates/article/article_list.html
{% extends "base.html" %}
{% block title %}Welcome To News Blog{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="landing">           
        </div>
        <!-- class="row news_list_class" -->
        <div class="row news_list_class">
            {% for article in articles %}
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 ">
                <a href="{% url 'article:detail' article.id %}">
                    <h2 style="text-decoration: underline;">{{ article.title }}</h2>
                    <div class="row">
                        <div class="col">
                            <p class="summary">{{ article.summary }}</p>
                        </div>
                        <div class="col">
                            {% if article.image %}
                                <img src="{{ article.image.url }}" alt="{{ article.title }}" style="max-width: 100%; height: auto;">    
                            {%endif%}
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

article/templates/article/comment_update.html
{% extends "base.html" %}
{% load crispy_forms_tags %} 

{% load static %}
{% block title %}{{article.title}}{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row mt-3 pt-3 mx-2">

            <div class="col-12 col-sm-12 col-md-12 col-lg-8 article_detail_class">
                <h1>{{ article.title }}</h1>
                <p style="margin-top: 1rem; color: grey; font-style: italic;">By {{ article.author.first_name }} {{ article.author.last_name }} on {{ article.published_date }}</p>
            
                {% if article.image %}
                    <img src="{{article.image.url }}" alt="{{ article.title }}">
                {% else %}
                    <p>No image available for this article.</p>
                {% endif %}
            
                <div class="mb-5 article_content_class">
                    {{ article.content }}
                </div>
                <div class="update-buttons" style=" display: flex; justify-content: space-between;">
                    <div  class="btn detail_buttton" >
                        <a href="{% url 'article:article_list' %}" type="button">Article List</a>
                    </div>
                </div>
            
            </div>
            <div id="article-list-tag" class="col-12 col-sm-12 col-md-12 col-lg-4 mt-5 pt-5 article_list">
                <h2>Here Are The Latest:</h2>
                {% for article in article_list %}
                    <h5>
                        <a href="{% url 'article:detail' article.id %}">{{ article.title }}</a>
                    </h5>
                {%endfor%}
                <div class="mt-5 comment-article" >
                    {% for comment in comments %}
                        <div style="display: flex;">
                            <div>
                                <i class="fas fa-user"></i>
                                <span style="color: #603F26; font-weight: bolder;">{{ comment.user.username }} -</span>
                                <span style="color: #6C4E31;">created on <small style="color: #b1afae;">{{ comment.created_at }}</small></span>
                                <p>{{ comment.content }}</p>
                            </div>
                            <div class="mx-2">
                                {% if comment.user == user %}
                                    <a href="{% url 'article:edit_comment' comment.id %}" type="button"><i class="fas fa-pen"></i></a>
                                {% endif %}
                            </div>                 
                        </div>
                    {%endfor%}
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form|crispy}}
                        <input style="border: none; background-color: #603F26; color: white;" type="submit" value="Submit">
                    </form>
                </div>
            </div>
        
        </div>
    </div>
    
{% endblock %}

article/templates/article/create_article.html
{% extends "base.html" %}
{% load crispy_forms_tags %} 
{% block title %}Add an Article{% endblock %}

{% block content %}
    <form id="parentFormSubmitBtn" action="" method="post" enctype="multipart/form-data" class="my-5" >
        <h1>Add an article</h1><br>
        {% csrf_token %}
        <div class="form row">
            <div class="form-group col-12 col-sm-12 col-md-6 col-lg-6 mb-3" style="color: #603F26">
                {{ form.title|as_crispy_field }}              
                {{ form.summary|as_crispy_field }}        
                {{ form.image|as_crispy_field }}              
      
            </div>
            <div class="form-group col-12 col-sm-12 col-md-6 col-lg-6 mb-3">
                {{ form.published_date|as_crispy_field }}              
                {{ form.author|as_crispy_field }}              
                {{ form.content|as_crispy_field }}              
            </div>
        </div>
        <input id="formSubmitBtn" class="py-2 px-3 text-white fw-bold" style="background-color: #603F26; border: none;" type="submit" value="Submit">
    </form>

    <!-- Nested Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header" style="display: flex; justify-content: center;">
                    <h5 class="modal-title" id="nestedModalLabel">Article Successfully added!</h5>
                </div>
                <div class="modal-body text-center">
                    <i style="font-size: 5rem; font-weight: bolder; color: #10eb08;" class="fas fa-check"></i>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn" style="background-color: #603F26; color: white;" data-bs-dismiss="modal">
                        <a href="{% url 'article:article_list' %}" style="text-decoration: none; color: white;">Back to Articles</a>
                    </button>
                </div>
            </div>
        </div>
    </div>              
    
{% endblock %}

article/templates/article/detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %} 

{% load static %}
{% block title %}{{article.title}}{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row mt-3 pt-3 mx-2">

            <div class="col-12 col-sm-12 col-md-12 col-lg-8 article_detail_class">
                <h1>{{ article.title }}</h1>
                <p style="margin-top: 1rem; color: grey; font-style: italic;">By {{ article.author.first_name }} {{ article.author.last_name }} on {{ article.published_date }}</p>
            
                {% if article.image %}
                    <img src="{{article.image.url }}" alt="{{ article.title }}">
                {% else %}
                    <p>No image available for this article.</p>
                {% endif %}
            
                <div class="mb-5 article_content_class">
                    {{ article.content }}
                </div>
                <div class="update-buttons" style=" display: flex; justify-content: space-between;">
                    <div  class="btn detail_buttton" >
                        <a href="{% url 'article:article_list' %}" type="button">Article List</a>
                    </div>
                    <div>
                        <div class="btn btn-primary" style="padding: 1rem; font-weight: bold;">
                            <a href="{% url 'article:update' article.id %}"  type="button" style="text-decoration: none; color: white">
                                Update
                            </a>
                        </div>

                        <div class="btn btn-danger" style="padding: 1rem; font-weight: bold;">
                            <a href="#!" type="button"  style="text-decoration: none; color: white" data-bs-toggle="modal" data-bs-target="#exampleModalLong"> 
                                Delete
                            </a>
                        </div>
                    </div>
                </div>
            
            </div>
            <div id="article-list-tag" class="col-12 col-sm-12 col-md-12 col-lg-4 mt-5 pt-5 article_list">
                <h2>Here Are The Latest:</h2>
                {% for article in article_list %}
                    <h5>
                        <a href="{% url 'article:detail' article.id %}">{{ article.title }}</a>
                    </h5>
                {%endfor%}
                <div class="mt-5 comment-article" >
                        {% for comment in comments %}
                        <div style="display: flex;">
                            <div>
                                <i class="fas fa-user"></i>
                                <span style="color: #603F26; font-weight: bolder;">{{ comment.user.username }} -</span>
                                <span style="color: #6C4E31;">created on <small style="color: #b1afae;">{{ comment.created_at }}</small></span>
                                <p>{{ comment.content }}</p>
                            </div>
                            <div class="mx-2">
                                {% if comment.user == user %}
                                    <a href="{% url 'article:edit_comment' comment.id %}" type="button"><i class="fas fa-pen"></i></a>
                                {% endif %}
                            </div>                 
                        </div>
                        {%endfor%}
                        <h3>Add a comment:</h3>

                        {% if user.is_authenticated %}
                            <form action="" method="post">
                                {% csrf_token %}
                                {{ form|crispy}}
                                <input style="border: none; background-color: #603F26; color: white;" type="submit" value="Submit">
                            </form>
                        {% else %}
                            <p>You must be <a style="color: #603F26; text-decoration: underline;" href="{% url 'login' %}">logged in</a> to add a comment.</p>
                        {% endif %}

                    <!-- <form action="" method="post">
                        {% csrf_token %}
                        {{ form|crispy}}
                        <input style="border: none; background-color: #603F26; color: white;" type="submit" value="Submit">
                    </form> -->
                </div>
            </div>
        
        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" style="display: flex; justify-content: space-between;">
                <h5 class="modal-title" id="exampleModalLong">Delete This Article</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color: white; font-weight: bold; border: none; background-color: #603F26;">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure about deleting this article? Deletion can't be undone!</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form id="articleDeleteBtnForm" action="{% url 'article:delete' article.id %}">
                    {% csrf_token %}
                    <button id="articleDeleteBtn" type="button" class="btn btn-danger" style="text-decoration: none;" >Delete</button>
                </form>
            </div>
        </div>
        </div>
    </div>

    <!-- Nested Modal -->
    <div class="modal fade" id="nestedModalDeleteArticle" tabindex="-1" aria-labelledby="nestedModalLabelDeleteArticle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header" style="display: flex; justify-content: center;">
                    <h5 class="modal-title" id="nestedModalLabelDeleteArticle">Successfully deleted!</h5>
                </div>
                <div class="modal-body text-center">
                    <i style="font-size: 5rem; font-weight: bolder; color: #10eb08;" class="fas fa-check"></i>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn" style="background-color:#603F26; color: white;" data-bs-dismiss="modal">
                        <a href="{% url 'article:article_list' %}" style="text-decoration: none; color: white;">Back to Articles</a>
                    </button>
                </div>
            </div>
        </div>
    </div>   
    
    <!-- Permission denied modal -->
    <div class="modal fade" id="1223345ModalArticleUpdate" tabindex="-1" aria-labelledby="1223345ModalLabelArticleUpdate" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header" style="display: flex; justify-content: center;">
                    <h5 class="modal-title" id="1223345ModalLabel">Permission Denied!</h5>
                </div>
                <div class="modal-body text-center">
                    <i style="font-size: 5rem; font-weight: bolder; color: #f31000;" class="fas fa-hippo"></i>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn" style="background-color: #603F26; color: white;" data-bs-dismiss="modal">
                        <a href="{% url 'article:article_list' %}" style="text-decoration: none; color: white;">Back to Articles</a>
                    </button>
                </div>
            </div>
        </div>
    </div>              
    
{% endblock %}

article/templates/article/update_article.html
{% extends "base.html" %}
{% load crispy_forms_tags %} 
{% block title %}Add an Article{% endblock %}

{% block content %}
    <form id="parentFormSubmitBtnUpdateArticle" action="" method="post" enctype="multipart/form-data" class="my-5" style="margin-left: 5rem; margin-right: 5rem;">
        <h1>Add an article</h1><br>
        {% csrf_token %}
        <!-- <div>
             {{ form|crispy }}
        </div> -->
        <div class="form row">
            <div class="form-group col-12 col-sm-12 col-md-6 col-lg-6 mb-3 mb-3" style="color: #603F26">
                {{ form.title|as_crispy_field }}              
                {{ form.summary|as_crispy_field }}        
                {{ form.image|as_crispy_field }}              
      
            </div>
            <div class="form-group col-12 col-sm-12 col-md-6 col-lg-6 mb-3 mb-3">
                {{ form.published_date|as_crispy_field }}              
                {{ form.author|as_crispy_field }}              
                {{ form.content|as_crispy_field }}              
            </div>
        </div>

        <br>
        <input id="submitBtnModalArticleUpdate" class="py-2 px-3 text-white fw-bold" style="background-color: #603F26; border: none;" type="submit" value="Submit">
    </form>

    <!-- Nested Modal -->
    <div class="modal fade" id="exampleModalArticleUpdate" tabindex="-1" aria-labelledby="exampleModalLabelArticleUpdate" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header" style="display: flex; justify-content: center;">
                    <h5 class="modal-title" id="nestedModalLabel">Article Successfully updated!</h5>
                </div>
                <div class="modal-body text-center">
                    <i style="font-size: 5rem; font-weight: bolder; color: #10eb08;" class="fas fa-check"></i>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn" style="background-color: #603F26; color: white;" data-bs-dismiss="modal">
                        <a href="{% url 'article:article_list' %}" style="text-decoration: none; color: white;">Back to Articles</a>
                    </button>
                </div>
            </div>
        </div>
    </div>              


    

{% endblock %}