article/urls.py
from django.urls import path

from .views import ArticleListView, ArticleCreateView, ArticleDetailView,CommentUpdateView, ArticleUpdateView, ArticleDeleteView

app_name = "article"
urlpatterns = [
    path('', ArticleListView.as_view(), name="article_list"),
    path('article/<int:pk>/detail/', ArticleDetailView.as_view(), name="detail"),
    path('article/<int:pk>/update/', ArticleUpdateView.as_view(), name="update"),
    path('article/<int:pk>/delete/', ArticleDeleteView.as_view(), name="delete"),
    path('article/<int:pk>/comment', CommentUpdateView.as_view(), name="edit_comment"),
    path('create_article/', ArticleCreateView.as_view(), name="create_article"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("signup.urls")),
    path('', include("article.urls")),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    bio = models.TextField(null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Article(models.Model):
    title = models.CharField(max_length=200)
    summary = models.TextField()
    content = models.TextField()
    published_date = models.DateTimeField(default=datetime.datetime.today)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='articles/images/', blank=True, null=True)

    def __str__(self):
        return self.title
    
class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Comment by {self.user} on {self.article}'

article/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'summary','published_date', 'author', 'content',  'image']
        widgets = {
            'published_date': forms.DateInput(attrs={'type': 'date'}),
            'summary': forms.Textarea(attrs={'rows': 3}),
            'content': forms.Textarea(attrs={'rows': 7})
        }

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'rows': 4}),
        }

article/views.py
from django.http import  JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic.edit import UpdateView, DeleteView, CreateView, FormMixin
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin


from .models import Article, Comment

from .forms import ArticleForm, CommentForm


class ArticleListView(ListView):
    model = Article
    template_name = "article/article_list.html"
    context_object_name = "articles"
    ordering = ['-published_date']  # Order articles by published date in descending order


class ArticleDetailView(FormMixin, DetailView):
    model = Article
    template_name = "article/detail.html"
    context_object_name = "article"
    form_class = CommentForm


    def get_success_url(self):
        return reverse('article:detail', kwargs={'pk': self.object.pk})
    
    def get_context_data(self, **kwargs):

        # Add additional context (latest articles) and comments to the template
        context = super().get_context_data(**kwargs)
        context['article_list'] = Article.objects.order_by("-published_date")[:10]
        context['comments'] = self.object.comments.all()

        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()

        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = self.object
            comment.user = request.user
            comment.save()
            return redirect(self.get_success_url())
        else:
            return self.form_invalid(form)

class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = "article/comment_update.html"

    def get_success_url(self):
        return reverse('article:detail', kwargs={'pk': self.object.article.pk})

    def get_context_data(self, **kwargs):

        # Add additional context (latest articles) and comments to the template
        context = super().get_context_data(**kwargs)
        context['article_list'] = Article.objects.order_by("-published_date")[:10]
        context['article'] = self.object.article
        context['comments'] = self.object.article.comments.all()
        # print(context['article'].values)
        return context

    def test_func(self):
        comment = self.get_object()
        return comment.user == self.request.user  # Check if the current user is the comment owner
    

class ArticleCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Article
    form_class = ArticleForm
    template_name = 'article/create_article.html'
    context_object_name = 'article'
    permission_required = 'article.add_article'

    def form_valid(self, form):
        # Handle valid form submission and save the form
        form.save()
        return JsonResponse({'success': True})

    def form_invalid(self, form):
        # Handle invalid form submission and return errors as JSON
        errors = {field: error.get_json_data(escape_html=True) for field, error in form.errors.items()}
        return JsonResponse({'success': False, 'errors': errors})



class ArticleDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Article
    context_object_name = 'article'
    permission_required = 'article.delete_article'


    def delete(self, request, *args, **kwargs):
        # Override delete to return a JSON response
        self.object = self.get_object()
        self.object.delete()
        return JsonResponse({'success': True})

    def post(self, request, *args, **kwargs):
        # Delegate POST requests to the delete method
        return self.delete(request, *args, **kwargs)


class ArticleUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Article
    form_class = ArticleForm
    template_name = 'article/update_article.html'
    context_object_name = 'article'
    permission_required = 'article.change_article'


    def form_valid(self, form):
        # If the form is valid, save it and return a success response
        form.save()
        return JsonResponse({'success': True})

    def form_invalid(self, form):
        # If the form is invalid, return errors as JSON
        errors = {field: error.get_json_data(escape_html=True) for field, error in form.errors.items()}
        return JsonResponse({'success': False, 'errors': errors})






#Article list
# def index(request):
#     article = Article.objects.order_by('-published_date')
#     return render(request , "article/article_list.html", {"article": article})


# Update article
# Update views
# def update(request, id):
#     article = get_object_or_404(Article, pk=id)
#     if request.method == 'POST':
#         form = ArticleForm(request.POST, instance=article)
#         if form.is_valid():
#             form.save()
#             return JsonResponse({'success': True})
#         else:
#             errors = {field: error.get_json_data(escape_html=True) for field, error in form.errors.items()}
#             return JsonResponse({'success': False, 'errors': errors})  
#     else:
#         form = ArticleForm(instance=article)
#     return render(request, 'article/update_article.html', {'form': form})


# Delete view
# def delete(request, id):

#     article = get_object_or_404(Article, pk=id)

#     if request.method == 'POST':

#         article.delete()

#         return JsonResponse({'success': True})
    
#     return JsonResponse({'success': False, 'errors': 'Invalid request method'})  

# Create article
# def detail(request, id):
#     article_list = Article.objects.order_by("-published_date")[:15]
#     article = get_object_or_404(Article, pk=id)
#     return render(request, "article/detail.html", {"article": article, "article_list": article_list})

# # def create_article(request):
#     if request.method == 'POST':
#         form = ArticleForm(request.POST, request.FILES)
#         if form.is_valid():
#             print(request.FILES)
#             form.save()
#             return JsonResponse({'success': True})
#         else:
#             errors = {field: error.get_json_data(escape_html=True) for field, error in form.errors.items()}
#             return JsonResponse({'success': False, 'errors': errors})  
#     else:
#         form = ArticleForm()
#     return render(request, 'article/create_article.html', {'form': form})

article/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'article/css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <title>{% block title %}Welcome{% endblock %}</title>

  <script src="{% static 'article/js/scripts.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light p-3">
      <div class="container">

        <a class="navbar-brand" href="{% url 'article:article_list' %}">NEWS BLOGS!</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span style="border-color: white;" class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ms-auto mt-2">
            <a class="nav-item nav-link active" href="{% url 'article:article_list' %}">Article List <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'article:create_article' %}">Add Article</a>
          </div>
          {% if user.is_authenticated %}
            <div class="connection-section">
              <div style="margin-right: .1rem;background-color: rgb(13, 206, 13); height: 10px; width: 10px; display: flex; align-items: center; color: white; border-radius: 50%;"></div>
              <span style="margin-right: 1.5rem">{{ user.username }}</span>
              <form style="margin: 0;" id="logout-form" method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button style="color: white; text-decoration: none;" type="submit" class="btn btn-link">Logout</button>
              </form>            
              {% else %}
                <div class="login-section" style="text-decoration: none; margin-left: 5rem;"><a style="color: rgb(133, 131, 131);"  href="{% url 'login' %}?next={{ request.path }}">Login</a></div>
              </div>
          {% endif %}
        </div>
      </div>
    </nav>
    {% block content %}
    {% endblock %}
    <!-- Footer -->
    <!-- Footer -->
    <footer class="text-center text-lg-start bg-body-tertiary text-muted">

      <!-- Section: Links  -->
      <section class="">
        <div class="container text-center text-md-start mt-5 pt-5">
          <!-- Grid row -->
          <div class="row mt-3">
            <!-- Grid column -->
            <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
              <!-- Content -->
              <a href="{% url 'article:article_list' %}">           
                <h6 class="text-uppercase fw-bolder mb-4">
                  <i class="fas fa-gem me-3"></i>News Blog
                </h6>
              </a>
              <p>
                Here you can find the latest news about the world. Discover what you don't usually hear about.
              </p>
            </div>
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
              <!-- Links -->
              <h6 class="text-uppercase fw-bolder mb-4">
                Useful links
              </h6>
              <p style="text-align: center;">
                <a href="{% url 'article:article_list' %}" class="text-reset">Artcle List</a>
              </p>
              <p style="text-align: center;">
                <a href="{% url 'article:create_article' %}" class="text-reset">Add Article</a>
              </p>
            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
              <!-- Links -->
              <h6 class="text-uppercase fw-bolder mb-4">Contact</h6>
              <p><i class="fas fa-home me-3"></i>Guinea - Conakry</p>
              <p>
                <i class="fas fa-envelope me-3"></i>
                info@alphonse.com
              </p>
              <p><i class="fas fa-phone me-3"></i> 623 00 00 00</p>
              <p><i class="fas fa-print me-3"></i> 611 00 33 99</p>
            </div>
            <!-- Grid column -->
          </div>
          <!-- Grid row -->
        </div>
      </section>
      <!-- Section: Links  -->

      <!-- Section: Social media -->
      <section class="d-flex justify-content-center justify-content-lg-between p-4">
        <!-- Left -->
        <div class="me-5 d-none d-lg-block">
          <span style="font-weight: bold; font-size: 1.2rem;">Get connected with us on social networks:</span>
        </div>
        <!-- Left -->

        <!-- Right -->
        <div>
          <a href="#!" class="me-4 text-reset">
            <i class="fab fa-facebook-f"></i>
          </a>
          <a href="#!" class="me-4 text-reset">
            <i class="fab fa-twitter"></i>
          </a>
          <a href="#!" class="me-4 text-reset">
            <i class="fab fa-google"></i>
          </a>
          <a href="#!" class="me-4 text-reset">
            <i class="fab fa-instagram"></i>
          </a>
          <a href="#!" class="me-4 text-reset">
            <i class="fab fa-linkedin"></i>
          </a>
          <a href="#!" class="me-4 text-reset">
            <i class="fab fa-github"></i>
          </a>
        </div>
        <!-- Right -->
      </section>
      <!-- Section: Social media -->


      <!-- Copyright -->
      <div class="text-center p-4 copyright_class" >
        © 2024 Copyright:
        <a class="text-reset fw-bold" href="#!">Alphonse KAMAN</a>
      </div>
      <!-- Copyright -->
    </footer>
    <!-- Footer -->  <!-- Footer -->

<!-- <script src="{% static 'js/scripts.js' %}"></script> -->

</body>
</html>